// Generated by CoffeeScript 1.12.7

/*
 * -------------------------------------------------------------------------- #
 * Center for Environmental Genomics
 * Copyright (C) 2009-2013 University of Washington.
 *
 * Authors:
 * Vaughn Iverson
 * vsi@uw.edu
 * -------------------------------------------------------------------------- #
 * This file is part of SEAStAR.
 *
 * SEAStAR is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SEAStAR is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SEAStAR.  If not, see <http:#www.gnu.org/licenses/>.
 * -------------------------------------------------------------------------- #
 */

(function() {
  var inputJSON, norm, ver, walk;

  ver = process.version.slice(1).split('.');

  if (!(ver[1] >= 10 || ver[0] > 0)) {
    console.error("ERROR: nodejs version v0.10.0 or greater required.");
    process.exit(1);
  }

  norm = 1.0;

  walk = function(tree) {
    var c, child, children, outstr, ref;
    outstr = '';
    if (tree.sub != null) {
      children = [];
      ref = tree.sub;
      for (c in ref) {
        child = ref[c];
        child.label = c;
        children.push(walk(child));
      }
      return outstr = "(" + (String(children)) + ")[&pop=" + (Math.round(10000.0 * tree.pop / norm) / 10000.0) + ",&tax=" + tree.label + ",&label=" + tree.label + "  " + (Math.round(10000.0 * tree.pop / norm) / 100.0) + "%]:" + tree.length;
    } else {
      return outstr = "'" + tree.conf + "   " + tree.label + "   " + (Math.round(10000.0 * tree.pop / norm) / 100.0) + "%':" + tree.length;
    }
  };

  inputJSON = '';

  process.stdin.setEncoding('utf8');

  process.stdin.resume();

  process.stdin.on('data', function(c) {
    return inputJSON = inputJSON.concat(c);
  });

  process.stdin.on('end', function() {
    var input_tree;
    input_tree = JSON.parse(inputJSON);
    input_tree.sub.Root.label = "Root";
    norm = input_tree.sub.Root.pop;
    process.stdout.write("#NEXUS\n\n begin trees;\n tree tree_1 = [&R] " + (walk(input_tree.sub.Root)) + ";\nend;\n");
    return process.exit(0);
  });

}).call(this);
